samplesheet: "../data/samplesheet.csv"
genome: "../BAM/merged/GRCm38.genome.fa"

outdir: "results"
threads: 30

mod_type: "5mC"
modkit_preset: "traditional"
modkit_extra: "--cpg --modified-bases 5mC"
mod_code: "m"
