# Set working directory
workdir: "/work/dir" 

#prefix of all output files:
sample_name: "sample"

# Reference genome as fasta
genome: "/path/to/genome.fa"

# Directory input data
fastq: "/directory/with/fastq/"
aligned_bam: "/directory/with/aligned_modBAM/"

# Options passed to minimap2 (optional)
minimap2_opts: ""

# Options passed to sniffles
sniffles_opts: "--minsvlen 50"

# threads (optional; default:30)
threads: 100
